name: michal-site
services:
  website:
    image: michal-site-website
    container_name: michal-site-website
    ports:
      - "5173:80"
    restart: unless-stopped

  server:
    image: michal-site-server
    container_name: michal-site-server
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - data_base

  data_base:
    image: postgres:17-alpine
    container_name: michal-site-db
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?error}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?error}
      POSTGRES_DB: ${POSTGRES_DB:?error}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
